<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Video;

/**
 * FavoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFavoriByUserAndVideo(User $user, Video $video)
    {
        return $this->createQueryBuilder('f')
            ->select('f')
            ->andWhere('f.user = :user')
            ->andWhere('f.video = :video')
            ->setParameters(['user' => $user, 'video' => $video])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
