<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Video;

/**
 * SignalementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalementRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Video $video
     * @param $adresseIp
     * @return mixed
     */
    public function getSignalementByVideoAndAdresseIp(Video $video, $adresseIp)
    {
        return $this->createQueryBuilder('s')
            ->select('s')
            ->andWhere('s.video = :video')
            ->andWhere('s.adresseIp = :adresseIp')
            ->setParameters(['video' => $video, 'adresseIp' => $adresseIp])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
