<?php

namespace AppBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVideoByUrl($url)
    {
        return $this->createQueryBuilder('v')
            ->select('v')
            ->andWhere('v.url = :url')
            ->setParameter(':url', $url)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
