<?php

namespace AppBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $url
     * @return mixed
     */
    public function getVideoByUrl($url)
    {
        return $this->createQueryBuilder('v')
            ->select('v')
            ->andWhere('v.url = :url')
            ->setParameter(':url', $url)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getTopVideos()
    {
        return $this->createQueryBuilder('v')
            ->select('v')
            ->andWhere('v.isActive = :isActive')
            ->andWhere('v.count > :count')
            ->setParameters([':isActive' => 1,':count' => 2])
            ->addOrderBy('v.count', 'DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }
}
