<?php

namespace AppBundle\Repository;

/**
 * VueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVueByVideoIdAndAdresseIp($videoId,$adresseIp)
    {
        return $this->createQueryBuilder('v')
            ->select('v')
            ->andWhere('v.videoId = :videoId')
            ->andWhere('v.adresseIp = :adresseIp')
            ->setParameters(['videoId'=> $videoId,'adresseIp' => $adresseIp])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
