# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments:
            - "@=service('doctrine').getManager()"
    app.video_manager:
        class: AppBundle\Manager\VideoManager
        arguments:
            - "@=service('doctrine').getManager()"
    app.vue_manager:
        class: AppBundle\Manager\VueManager
        arguments:
            - "@=service('doctrine').getManager()"
    app.favori_manager:
        class: AppBundle\Manager\FavoriManager
        arguments:
            - "@=service('doctrine').getManager()"
    app.reporting_manager:
        class: AppBundle\Manager\ReportingManager
        arguments:
            - "@=service('doctrine').getManager()"
